<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_24</name>
   <tag></tag>
   <elementGuidId>7c1e56ca-1f29-4676-9f8e-0f30195f5a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[62]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b1a3048-476d-4ddd-ab26-fa55b3214200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cab24ae3-9cc2-4980-9565-bc840c7d0af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>531ca661-7652-44dd-824c-399f8c375468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date</name>
      <type>Main</type>
      <value>2024-02-24</value>
      <webElementGuid>98c5823a-e3b1-4374-a7e6-18f809fc4f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>asd__day-button</value>
      <webElementGuid>47b53746-5eed-4add-99a9-2a7efa025e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>579a5241-0f99-4905-9adf-dc57707ec0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airbnb-style-datepicker-wrapper-7RXf1&quot;)/div[@class=&quot;asd__inner-wrapper&quot;]/div[1]/div[@class=&quot;asd__month&quot;]/table[@class=&quot;asd__month-table&quot;]/tbody[1]/tr[@class=&quot;asd__week&quot;]/td[@class=&quot;asd__day asd__day--enabled&quot;]/button[@class=&quot;asd__day-button&quot;]</value>
      <webElementGuid>565123a5-6bd7-46bf-9dc9-e45580f67125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[62]</value>
      <webElementGuid>90191fe4-8336-4ad5-855d-4f9ef8cd2d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='airbnb-style-datepicker-wrapper-7RXf1']/div[2]/div/div[2]/table/tbody/tr[4]/td[6]/button</value>
      <webElementGuid>5dfc1473-d5b5-447c-bc79-0b6716e6465e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February'])[1]/following::button[24]</value>
      <webElementGuid>5599098b-1ebd-4882-a14f-35e1ce9613ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January'])[1]/following::button[55]</value>
      <webElementGuid>85a2610e-00a9-4982-8f1b-b54a2f74bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March'])[1]/preceding::button[6]</value>
      <webElementGuid>55e3a7c7-9917-4d56-a2e6-b3b15fd26e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April'])[1]/preceding::button[37]</value>
      <webElementGuid>390b59d9-b029-4b22-ba6d-a0a3a1958654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[4]/td[6]/button</value>
      <webElementGuid>03694ff1-29d0-4a2f-ab63-2ecc6ea52b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '24' or . = '24')]</value>
      <webElementGuid>9b258f68-6c97-4ba9-97a2-f0db49b44e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
