<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_16</name>
   <tag></tag>
   <elementGuidId>b89f7324-c0e6-4b06-b288-5f8f638cb271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.asd__day.asd__day--enabled.asd__day--today > button.asd__day-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[54]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>665fe932-e93c-4065-8c14-bebb3546a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7596f26-d2db-4cea-b51f-c05cd269b53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d189ffd4-0a5e-40d0-88f6-16c6533eac04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date</name>
      <type>Main</type>
      <value>2024-02-16</value>
      <webElementGuid>07557018-e6a1-4700-ba99-2ddb5f4ff9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>asd__day-button</value>
      <webElementGuid>5faf8996-c0cb-4598-801b-86156929b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>636b3302-4e94-428d-9023-2bcf4ee859eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airbnb-style-datepicker-wrapper-7RXf1&quot;)/div[@class=&quot;asd__inner-wrapper&quot;]/div[1]/div[@class=&quot;asd__month&quot;]/table[@class=&quot;asd__month-table&quot;]/tbody[1]/tr[@class=&quot;asd__week&quot;]/td[@class=&quot;asd__day asd__day--enabled asd__day--today&quot;]/button[@class=&quot;asd__day-button&quot;]</value>
      <webElementGuid>2d2c7189-f06a-4ccd-92da-f123cee769ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[54]</value>
      <webElementGuid>f6ae00a6-b607-4e45-9c3c-a76de74da5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='airbnb-style-datepicker-wrapper-7RXf1']/div[2]/div/div[2]/table/tbody/tr[3]/td[5]/button</value>
      <webElementGuid>a890cf26-3fc9-49f1-bdfa-97c6032c30e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February'])[1]/following::button[16]</value>
      <webElementGuid>3f1adfbf-0f6a-4587-a67d-e1a0c0da006f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January'])[1]/following::button[47]</value>
      <webElementGuid>962a553f-f804-4d73-96f2-ad337809cc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March'])[1]/preceding::button[14]</value>
      <webElementGuid>ef5064a7-f787-4cc5-873e-182b6ac725c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April'])[1]/preceding::button[45]</value>
      <webElementGuid>83b20192-db0c-429a-9728-b7c68eb580ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[3]/td[5]/button</value>
      <webElementGuid>a8019329-527d-4bd4-a6bd-3db8b7e4d0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '16' or . = '16')]</value>
      <webElementGuid>116061c4-be5a-4341-a380-ed614e2e61f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
