<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Children_numChild</name>
   <tag></tag>
   <elementGuidId>c9ab464c-025c-4e2d-bfd5-3f6bdd832bd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#num_child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='num_child']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5003f362-df38-459b-9059-7e2b4a0bea77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>num_child</value>
      <webElementGuid>9bc5ea18-9789-4e7e-9d0f-1428ae2a2cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numChild</value>
      <webElementGuid>4b8789fc-f08c-4ccb-8a44-19ec4442b7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>26b68c2b-77ec-427b-8f96-d5d255674199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1030f1b-7ca2-44fe-955a-e890c37280af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>7684bb5b-d491-4a20-ac68-275ddc5c33ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;num_child&quot;)</value>
      <webElementGuid>3481996d-2f08-479d-a983-05cb8d9c7215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='num_child']</value>
      <webElementGuid>8964cd48-d022-4933-b58f-e9a10dd6663f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-booking-booker-section']/div/div/div[6]/div/input</value>
      <webElementGuid>7dbe254a-85ac-4f84-bd20-3654059974b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>166f12db-4ecb-46f7-944c-b3d5e4522ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'num_child' and @name = 'numChild' and @type = 'number']</value>
      <webElementGuid>09fb3594-6483-4091-b11b-ee0c96c65b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
