<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_phone-rjgq0fj</name>
   <tag></tag>
   <elementGuidId>022cd15c-7f00-46f4-907b-e596be7e372e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-rjgq0fj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-rjgq0fj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9163b550-6ab3-4648-9550-ed453e5d3fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>38bf97a6-a354-47ac-b519-2c537d1b7744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-rjgq0fj</value>
      <webElementGuid>43ce7466-f4fa-4eb9-b40e-6db7935b78ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b134ca6-49d5-4e2b-8faa-7b1331457ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e3ac1a42-14ef-4abf-969c-e37b7579b724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0301 2345678</value>
      <webElementGuid>d237a546-fc54-466c-ae75-8ec3af5ba30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-rjgq0fj&quot;)</value>
      <webElementGuid>50fb45ba-0df8-48a5-94df-f3fb9a949395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-rjgq0fj']</value>
      <webElementGuid>0a82cc63-e834-4164-923b-125aa8ba3e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-booking-booker-section']/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>a7b289d5-9579-4a18-b164-e32cdee1cc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>0ebe2daf-c8c8-4e68-b5bf-6eecdc93c335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'phone-rjgq0fj' and @placeholder = '0301 2345678']</value>
      <webElementGuid>8fac39a3-78e7-4a51-84db-d658ad14885c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
