<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adults_numAdults</name>
   <tag></tag>
   <elementGuidId>b604c8a0-029d-4cca-9ebd-7def210830d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#num_adults</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='num_adults']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a5165e-5fe7-40ab-8fab-2cab1e136e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>num_adults</value>
      <webElementGuid>e42a3339-311e-4a7c-abe2-356603f3d181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numAdults</value>
      <webElementGuid>b60dff05-671d-4688-8164-f8ce431f0d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9ddc5c37-047e-41d6-a2f1-10925e2422d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbc72f13-6a0e-4d2e-8206-04c7e20e262b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>f13ffac6-a4f3-453f-b660-3b6aaa3d3c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;num_adults&quot;)</value>
      <webElementGuid>de77841b-2d29-4958-9727-a2a15cca2d82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='num_adults']</value>
      <webElementGuid>d2cfc0b6-2344-4fa3-8282-6021927bb44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-booking-booker-section']/div/div/div[5]/div/input</value>
      <webElementGuid>c8fb8bc8-5770-4504-80f6-9eed84e4c909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>fd38c942-fb08-44ab-9d12-befc97b58458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'num_adults' and @name = 'numAdults' and @type = 'number']</value>
      <webElementGuid>d12b93fb-a7bf-4ae2-be84-325893230f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
