<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_phone-rjgq0fj_1</name>
   <tag></tag>
   <elementGuidId>e353d5a9-5b19-4a9e-ae21-cd3d09ace8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-rjgq0fj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-rjgq0fj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d986c16b-93fd-4f13-8559-241986290220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>35177753-e94b-4374-9e1a-79a2a94d87e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-rjgq0fj</value>
      <webElementGuid>9b95da57-8918-40d2-91b4-3f17be5cf69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a62035b-1380-453b-99c5-4918003508c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cf198a11-c234-47e3-840b-a495a54f4cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-rjgq0fj&quot;)</value>
      <webElementGuid>655b85de-2ac1-4032-bb14-bf87c2136351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-rjgq0fj']</value>
      <webElementGuid>0c61f8fc-64d6-4018-8a46-e1e03bdd4906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-booking-booker-section']/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>08bc7ef3-5366-4654-b347-10f141fdab64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>5a9e7439-7807-4d78-9228-f4c52c7a1133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'phone-rjgq0fj']</value>
      <webElementGuid>505227cb-ce39-4edc-8de5-0100a413412f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
