<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Source Direct                _5c3c43</name>
   <tag></tag>
   <elementGuidId>06fe61d4-fd7d-45be-9d51-c172f16f49ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_source</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='booking_source']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7e8e6125-d0be-4bb5-b5f7-c841e2edbe3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>booking_source</value>
      <webElementGuid>dcf31e8a-ba25-4942-a48a-8db0492d84ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select-arrow form-control</value>
      <webElementGuid>04fffa5f-e6d6-4c5e-84a4-645f40d49867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Source Direct
                                        NewBS
                                        TEST_PMS_NO_PMS
                                        TEST_PMS_NO_PMS_2
                                        TEST-AP-UPSELL-ADMIN
                                        TEST_NO_PMS
                                        </value>
      <webElementGuid>4c3a2469-135b-47de-91a5-c8d79886b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_source&quot;)</value>
      <webElementGuid>ea983465-b9c7-42d1-854d-b57d678efcee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='booking_source']</value>
      <webElementGuid>9dc72edc-48d3-4b8b-9e8b-919e663b7d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookings-tabContent']/div/div[2]/div[2]/div/select</value>
      <webElementGuid>0abfd3bb-1359-49e9-aeef-3f98415567cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>4fccaa1c-098d-411e-9f8f-afc8893f666c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>bfb1c8ed-03ca-414f-9921-65ce72c2e277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>b1b9eb49-3b1b-4c2f-a2ed-a02e856dcc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'booking_source' and (text() = 'Select Source Direct
                                        NewBS
                                        TEST_PMS_NO_PMS
                                        TEST_PMS_NO_PMS_2
                                        TEST-AP-UPSELL-ADMIN
                                        TEST_NO_PMS
                                        ' or . = 'Select Source Direct
                                        NewBS
                                        TEST_PMS_NO_PMS
                                        TEST_PMS_NO_PMS_2
                                        TEST-AP-UPSELL-ADMIN
                                        TEST_NO_PMS
                                        ')]</value>
      <webElementGuid>26ee90cf-fb48-44fa-97c6-acded7404743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
