<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Internal Notes_bookingNotes</name>
   <tag></tag>
   <elementGuidId>8be3f562-59ae-4a4b-a5b1-3b307628d12d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='bookingNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>30f94138-333a-4feb-836a-18734c5a438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingNotes</value>
      <webElementGuid>747e5909-36a3-47ad-991b-0b05446473ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Internal notes</value>
      <webElementGuid>66e151a5-451e-4bfb-9b28-0ab3ae82a161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>502d2d80-e3fb-4b28-af4e-6af8c0342143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>8e1f2535-a5a5-422c-ac25-4936b1220da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingNotes&quot;)</value>
      <webElementGuid>f4b49354-d58b-4f6e-b026-0118ef994e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='bookingNotes']</value>
      <webElementGuid>518075b7-326b-4bb7-ab2d-02d4e900cf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookings-tabContent']/div/div[5]/div/div/div/textarea</value>
      <webElementGuid>8e8e4f4f-c03f-473a-8c2b-5825dcbaf90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/textarea</value>
      <webElementGuid>be954b67-d6a0-45a0-926e-dcdc0946635b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'bookingNotes' and @placeholder = 'Internal notes' and @type = 'number']</value>
      <webElementGuid>1d560427-bcaf-4711-827c-0ecea2ae1a0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
